/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.inte_soft.gestionconsumibles.formularios;

import com.inte_soft.gestionconsumibles.controller.PedidoConsumiblesController;
import com.inte_soft.gestionconsumibles.dto.EntregaDto;
import com.inte_soft.gestionconsumibles.entity.Ot;
import com.inte_soft.gestionconsumibles.entity.Usuarios;
import com.inte_soft.gestionconsumibles.util.ModelarTabla;

import javax.swing.table.DefaultTableModel;
import java.math.BigInteger;
import java.util.List;

/**
 *
 * @author Usuario
 */
public class EntregaConsumibles extends javax.swing.JDialog {

    private Usuarios usuarios;
    private List<String> listItem;
    private String area;
    private Ot ot;
    private String codigo;
    private PedidoConsumiblesController pedidoConsumiblesController;
    private List<EntregaDto> consumiblesEntregaDto;
    private ModelarTabla modelarTabla;
    private DefaultTableModel model;
    private ListadoPendiente listadoPendiente;

    /**
     * Creates new form entregaConsumibles
     */
    public EntregaConsumibles() {
        initComponents();
    }

    public EntregaConsumibles(Usuarios usuarios, List<String> listItem, String area, Ot ot, String codigo, ListadoPendiente listadoPendiente){
        initComponents();
        this.usuarios = usuarios;
        this.listItem = listItem;
        this.area = area;
        this.ot = ot;
        this.pedidoConsumiblesController = new PedidoConsumiblesController();
        this.modelarTabla = new ModelarTabla(jTable1);
        this.model = modelarTabla.getModel();
        this.codigo = codigo;
        this.listadoPendiente = listadoPendiente;
        loadConsumibles();
    }

                              /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                              @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ot", "Item", "Codigo", "Descripción", "Tipo", "Referencia", "Marca", "Unidad", "Cantidad", "Entregado", "Pendiente", "Obcervaciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1184, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        stopEditing();
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            for (EntregaDto entregaDto : consumiblesEntregaDto) {
                if (entregaDto.getId().equals(BigInteger.valueOf(Integer.parseInt( jTable1.getValueAt(i, 0).toString())))) {
                    entregaDto.setAlistado(Double.parseDouble(jTable1.getValueAt(i, 10).toString()));
                    entregaDto.setObservacion(jTable1.getValueAt(i, 12).toString());
                }
            }
        }
        pedidoConsumiblesController.updateEntregaConsumibles(consumiblesEntregaDto);
        listadoPendiente.loadConsumibles();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void stopEditing(){
        if (jTable1.isEditing()) {
            jTable1.getCellEditor().stopCellEditing();
        }
    }
    private void loadConsumibles(){
        consumiblesEntregaDto = pedidoConsumiblesController.getConsumiblesByOtAndItemUnicConsumible(ot, listItem, area, codigo);
        model.setRowCount(0);
        for(EntregaDto entregaDto : consumiblesEntregaDto){
            if (entregaDto.getObservacion() == null) {
                entregaDto.setObservacion("");
            }
            model.addRow(
                    new Object[]{
                            entregaDto.getId(),
                            entregaDto.getOt(),
                            entregaDto.getItem(),
                            entregaDto.getCodigo(),
                            entregaDto.getDescripcion(),
                            entregaDto.getTipo(),
                            entregaDto.getReferencia(),
                            entregaDto.getMarca(),
                            entregaDto.getUnidad(),
                            entregaDto.getCantidad(),
                            entregaDto.getAlistado(),
                            entregaDto.getCantidad() - entregaDto.getAlistado(),
                            entregaDto.getObservacion()
                            });
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
