/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.inte_soft.gestionconsumibles.formularios;

import com.inte_soft.gestionconsumibles.controller.UsuariosController;
import com.inte_soft.gestionconsumibles.dto.UsuariosDto;
import com.inte_soft.gestionconsumibles.entity.Usuarios;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author alejo
 */
public class GestionUsuarios extends javax.swing.JInternalFrame {
    /**
     * Creates new form GestionUsuarios
     */
    public GestionUsuarios() {
        
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        butonAddUser = new javax.swing.JButton();
        butonDeleteUser = new javax.swing.JButton();
        butonModifyUser = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombres", "Apellidos", "Area", "Almacen", "Ingenieria", "Admin User", "Compras", "Comercial", "Produccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableUser);
        if (tableUser.getColumnModel().getColumnCount() > 0) {
            tableUser.getColumnModel().getColumn(0).setResizable(false);
            tableUser.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableUser.getColumnModel().getColumn(9).setResizable(false);
        }

        butonAddUser.setText("Agregar");
        butonAddUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butonAddUserMouseClicked(evt);
            }
        });
        butonAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonAddUserActionPerformed(evt);
            }
        });

        butonDeleteUser.setText("Eliminar");
        butonDeleteUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butonDeleteUserMouseClicked(evt);
            }
        });

        butonModifyUser.setText("Modificar");
        butonModifyUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butonModifyUserMouseClicked(evt);
            }
        });

        jMenu1.setText("Menu");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(butonAddUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butonModifyUser)
                        .addGap(14, 14, 14)
                        .addComponent(butonDeleteUser)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butonAddUser)
                    .addComponent(butonDeleteUser)
                    .addComponent(butonModifyUser))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butonAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonAddUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butonAddUserActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked

        this.dispose();
        
    }//GEN-LAST:event_jMenu2MouseClicked

    private void butonAddUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butonAddUserMouseClicked

        User user = new User(this);
        user.setModal(true);
        user.setVisible(true);
        
    
    }//GEN-LAST:event_butonAddUserMouseClicked

    private void butonModifyUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butonModifyUserMouseClicked
        int rowIndex = this.tableUser.getSelectedRow();
        if(rowIndex >=0 ){
           UsuariosController usuariosController = new UsuariosController();
            Usuarios usuario = usuariosController.getById((int) this.tableUser.getValueAt(rowIndex, 0));
            User user = new User(usuario,this);
            user.setModal(true);
            user.setVisible(true);
            
            
        }else{
            JOptionPane.showMessageDialog(null, "No ha selecionado ningun usuario para modificar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_butonModifyUserMouseClicked

    private void butonDeleteUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butonDeleteUserMouseClicked
        int rowIndex = this.tableUser.getSelectedRow();
        if(rowIndex >=0 ){
            int option = JOptionPane.showOptionDialog(null, "Esta seguro que desea eliminar el usuario", "Confirmar",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if(option == JOptionPane.OK_OPTION){
            UsuariosController usuariosController = new UsuariosController();
            usuariosController.deleteUser((int) this.tableUser.getValueAt(rowIndex, 0));
            
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "No ha selecionado ningun usuario para eliminar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        this.loadUserData();
    }//GEN-LAST:event_butonDeleteUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionUsuarios gestionUsuarios = new GestionUsuarios();
                gestionUsuarios.setVisible(true); 
                gestionUsuarios.loadUserData();
            }
        });
        
    }
    public void loadUserData(){        
                DefaultTableModel model =  (DefaultTableModel) tableUser.getModel();
                UsuariosController usuariosController = new UsuariosController();
                List<UsuariosDto> listUsuariosDto = usuariosController.getAllUser();
                model.setRowCount(0);
                for(UsuariosDto usuarios: listUsuariosDto ){
                    Object[] rowData = {
                        usuarios.getIdUsuario(),
                        usuarios.getNombre(),
                        usuarios.getApellido(),
                        usuarios.getIdAreaCompañia(),
                        usuarios.getpAlmacen(),
                        usuarios.getpIngenieria(),
                        usuarios.getpAdminUser(),
                        usuarios.getpCompras(),
                        usuarios.getpComercial(),
                        usuarios.getpProduccion()
                    };
                    model.addRow(rowData);
                }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonAddUser;
    private javax.swing.JButton butonDeleteUser;
    private javax.swing.JButton butonModifyUser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableUser;
    // End of variables declaration//GEN-END:variables
}
