/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.inte_soft.gestionconsumibles.formularios;

import com.inte_soft.gestionconsumibles.controller.PedidoConsumiblesController;
import com.inte_soft.gestionconsumibles.dto.ConsumiblesDtoOt;
import com.inte_soft.gestionconsumibles.dto.PendientesDto;
import com.inte_soft.gestionconsumibles.util.ModelarTabla;
import com.inte_soft.gestionconsumibles.util.WindowSingleton;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.util.List;

/**
 *
 * @author alejo
 */
public class Pendientes extends javax.swing.JInternalFrame {

    private WindowSingleton windowSingleton;
    private DefaultTableModel model;
    private List<PendientesDto> consumiblesDtoOtList;

    private TableRowSorter<DefaultTableModel> sorter;

    private ModelarTabla modelarTabla;
    /**
     * Creates new form Pendientes
     */
    public Pendientes() {
        initComponents();
    }

    public Pendientes(WindowSingleton windowSingleton) {
        this.windowSingleton = windowSingleton;
        initComponents();
        this.model = modelarTabla(jTable1);
        loadPendientes();
    }
    public  DefaultTableModel modelarTabla(JTable jTable){
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        jTable.setModel(model);
        jTable.setAutoCreateRowSorter(true);
        sorter = new TableRowSorter<>(model);
        jTable.setRowSorter(sorter);
        return model;
    }
    @Override
    public void dispose() {
        super.dispose(); //To change body of generated methods, choose Tools | Templates.
        windowSingleton.setCloseWindow();
    }

    public void loadPendientes() {
        PedidoConsumiblesController pedidoConsumiblesController = new PedidoConsumiblesController();
        //la idea es traer todos los consumibles pendientes de alistamiento tanto electricos como mecanicos y mostrarlos en la tabla
        consumiblesDtoOtList = pedidoConsumiblesController.getConsumiblesPendientes();
        model.setRowCount(0);
        for (PendientesDto pendientesDto  : consumiblesDtoOtList) {
            model.addRow(new Object[]{
                    pendientesDto.getCodigo(),
                    pendientesDto.getDescripcion(),
                    pendientesDto.getTipo(),
                    pendientesDto.getReferencia(),
                    pendientesDto.getMarca(),
                    pendientesDto.getUnidad(),
                    pendientesDto.getCantidad(),
                    pendientesDto.getAlistado(),
                    pendientesDto.getCantidad()-pendientesDto.getAlistado(),
                    pendientesDto.getArea().replace("CONSUMIBLES ","")
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Tipo", "Referencia", "Marca", "Unidad", "Cantidad", "Alistado", "Pendiente", "Consumibles"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
