/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

import clases.conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Inte-Soft
 */
public class Almacen extends javax.swing.JInternalFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    public void buscar() {
        String sql = "";
        Date fecha1=jDateChooser1.getDate();
        Date fecha2=jDateChooser2.getDate();
        String eFechas;
        if (fecha1!=null || fecha2!=null ) {
            eFechas= " AND FECHA BETWEEN #"+fecha1.getDate()+"-"+fecha1.getMonth()+"-"+fecha1.getYear()+"# AND #"+fecha2.getDate()+"-"+fecha2.getMonth()+"-"+fecha2.getYear()+"#";
        } else {
            eFechas="";
        }
        
        DefaultTableModel modelo = (DefaultTableModel) tabla_Almacen.getModel();
        String registros[]= new String[8];
        switch (cb_buscar.getSelectedItem().toString()) {

            case "Codigo":

                sql = "select * not in(CODIGO),SUM(CANTIDAD) from PEDIDOS where CODIGO like '%" + txtcodigoAlmacen.getText() + "'"+eFechas+" GROUP BY CODIGO";

                break;

            case "Descripcion":

                sql = "select * not in(CODIGO),SUM(CANTIDAD) from PEDIDOS where DESCRIPCION like '%" + txtcodigoAlmacen.getText() + "%'"+eFechas+" GROUP BY CODIGO";

                break;
            case "OT":

                sql = "select * not in(CODIGO),SUM(CANTIDAD) from PEDIDOS where OT like '%" + txtcodigoAlmacen.getText() + "'"+eFechas+" GROUP BY CODIGO";

                break;
            case "Seleccione":

                sql = "select OT, CODIGO, DESCRIPCION, REFERENCIA, MARCA, UNIDAD, SUM(CANTIDAD) AS CANTIDAD, SUM(VALOR) AS VALOR from PEDIDOS where OT like '%" + txtcodigoAlmacen.getText() + "%'"+eFechas+"GROUP BY OT, DESCRIPCION, REFERENCIA, UNIDAD, CODIGO, MARCA";

                break;
            default:
                sql = "select * from PEDIDOS";
        }
        

        try{
            con = conexion.obtenerconexion();

            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while (rs.next()) {

                registros[0] = rs.getString("OT");
                registros[1] = rs.getString("CODIGO");
                registros[2] = rs.getString("DESCRIPCION");
                registros[3] = rs.getString("REFERENCIA");
                registros[4] = rs.getString("MARCA");
                registros[5] = rs.getString("UNIDAD");
                registros[6] = rs.getString("CANTIDAD");
                registros[7] = rs.getString("VALOR");
                modelo.addRow(registros);
                             
                
            }

        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    /**
     * Creates new form Almacen
     */
    public Almacen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb_buscar = new javax.swing.JComboBox<>();
        txtcodigoAlmacen = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_Almacen = new javax.swing.JTable();
        btn_Buscar = new javax.swing.JButton();
        btn_Limpiar = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Almacen");

        cb_buscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Codigo", "Descripcion", "OT" }));

        txtcodigoAlmacen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcodigoAlmacenKeyPressed(evt);
            }
        });

        jLabel1.setText("Buscar por:");

        jLabel2.setText("Busqueda:");

        jLabel3.setText("Desde");

        jLabel4.setText("Hasta");

        tabla_Almacen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OT", "CODIGO", "DESCRIPCION", "REFERENCIA", "MARCA", "UNIDAD", "CANTIDAD", "VALOR"
            }
        ));
        jScrollPane2.setViewportView(tabla_Almacen);

        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/enviar-mensaje.png"))); // NOI18N
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        btn_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cb_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtcodigoAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Buscar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Limpiar)))
                .addContainerGap(281, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcodigoAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_Buscar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Limpiar)))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed

    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void txtcodigoAlmacenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoAlmacenKeyPressed
      this.buscar();
    }//GEN-LAST:event_txtcodigoAlmacenKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Limpiar;
    private javax.swing.JComboBox<String> cb_buscar;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla_Almacen;
    private javax.swing.JTextField txtcodigoAlmacen;
    // End of variables declaration//GEN-END:variables
}
