/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Inte-Soft
 */
public class Menu extends javax.swing.JFrame {

    public Menu() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/proceso-de-trabajo.png")).getImage());
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_ventanaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmComercial = new javax.swing.JMenu();
        jmIngenieria = new javax.swing.JMenu();
        jmCompras = new javax.swing.JMenu();
        jmAlmacen = new javax.swing.JMenu();
        jmReportes = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jmAyuda = new javax.swing.JMenu();
        jAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IPA");

        javax.swing.GroupLayout jd_ventanaPrincipalLayout = new javax.swing.GroupLayout(jd_ventanaPrincipal);
        jd_ventanaPrincipal.setLayout(jd_ventanaPrincipalLayout);
        jd_ventanaPrincipalLayout.setHorizontalGroup(
            jd_ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1193, Short.MAX_VALUE)
        );
        jd_ventanaPrincipalLayout.setVerticalGroup(
            jd_ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );

        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagenesNuevas/carpeta.png"))); // NOI18N
        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Cerrar Sesion");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Salir del Sistema");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jmComercial.setForeground(new java.awt.Color(0, 0, 0));
        jmComercial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagenesNuevas/adquisitivo (1).png"))); // NOI18N
        jmComercial.setText("Comercial");
        jMenuBar1.add(jmComercial);

        jmIngenieria.setForeground(new java.awt.Color(0, 0, 0));
        jmIngenieria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagenesNuevas/prototipo (1).png"))); // NOI18N
        jmIngenieria.setText("Ingenieria");
        jmIngenieria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmIngenieriaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmIngenieria);

        jmCompras.setForeground(new java.awt.Color(0, 0, 0));
        jmCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagenesNuevas/bolsa-de-la-compra (1).png"))); // NOI18N
        jmCompras.setText("Compras");
        jMenuBar1.add(jmCompras);

        jmAlmacen.setForeground(new java.awt.Color(0, 0, 0));
        jmAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagenesNuevas/almacen.png"))); // NOI18N
        jmAlmacen.setText("Almacen");
        jmAlmacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAlmacenMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmAlmacen);

        jmReportes.setForeground(new java.awt.Color(0, 0, 0));
        jmReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagenesNuevas/reporte-de-negocios (1).png"))); // NOI18N
        jmReportes.setText("Reportes");
        jMenuBar1.add(jmReportes);

        jMenu2.setForeground(new java.awt.Color(0, 0, 0));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagenesNuevas/panel-de-administrador.png"))); // NOI18N
        jMenu2.setText("Administrar");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Usuarios");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu4.setForeground(new java.awt.Color(0, 0, 0));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagenesNuevas/configuracion.png"))); // NOI18N
        jMenu4.setText("Configuracion");

        jMenuItem4.setText("Conectar BD");
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        jmAyuda.setForeground(new java.awt.Color(0, 0, 0));
        jmAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagenesNuevas/ayuda.png"))); // NOI18N
        jmAyuda.setText("Ayuda");
        jmAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAyudaMouseClicked(evt);
            }
        });

        jAyuda.setText("Acerca de");
        jmAyuda.add(jAyuda);

        jMenuBar1.add(jmAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jd_ventanaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jd_ventanaPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmIngenieriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmIngenieriaMouseClicked
        Pedidos pedido = new Pedidos();
        jd_ventanaPrincipal.add(pedido);
        pedido.show();
    }//GEN-LAST:event_jmIngenieriaMouseClicked

    private void jmAlmacenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAlmacenMouseClicked
        Almacen almacen = new Almacen();
        jd_ventanaPrincipal.add(almacen);
        almacen.show();
    }//GEN-LAST:event_jmAlmacenMouseClicked

    private void jmAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAyudaMouseClicked
        Ayuda ayuda = new Ayuda();
        jd_ventanaPrincipal.add(ayuda);
        ayuda.show();
    }//GEN-LAST:event_jmAyudaMouseClicked

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAyuda;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JDesktopPane jd_ventanaPrincipal;
    private javax.swing.JMenu jmAlmacen;
    private javax.swing.JMenu jmAyuda;
    private javax.swing.JMenu jmComercial;
    private javax.swing.JMenu jmCompras;
    private javax.swing.JMenu jmIngenieria;
    private javax.swing.JMenu jmReportes;
    // End of variables declaration//GEN-END:variables
}
