/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

import clases.conexion;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import static java.time.Instant.now;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Inte-Soft
 */
public class Pedidos extends javax.swing.JInternalFrame {
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    int valor =0;
     
     public void buscar(){
            
            try{
                con=conexion.obtenerconexion();
                String sql = "select * from MAESTRO where CODIGO like '%"+txt_Codigo.getText() + "'";
                pst = con.prepareStatement(sql);
                rs = pst.executeQuery();
                while (rs.next()){
                  txt_Descripcion.setText(rs.getString("DESCRIPCION"));
                  txt_Tipo.setText(rs.getString("TIPO"));
                  txt_Referencia.setText(rs.getString("REFERENCIA"));
                  txt_Marca.setText(rs.getString("MARCA"));
                  txt_Unidad.setText(rs.getString("UNIDAD"));
                  valor=rs.getInt("PRECIO_DESCUENTO");
                }
                
                
            }catch(Exception ex){
                System.out.println(ex);
            }
        }
         public void enviar(){
             DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();   
            try{
                
                for (int i = 0; i < jTable1.getRowCount(); i++) {
                    con=conexion.obtenerconexion();
                    String sql = "INSERT INTO PEDIDOS (OT,ITEM,CODIGO,DESCRIPCION,TIPO,REFERENCIA,MARCA,UNIDAD,CANTIDAD,VALOR,ADICIONAL_INICIAL,FECHA,OPERACION,DEPARTAMENTO) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                    pst = con.prepareStatement(sql);
                    pst.setString(1,jTable1.getValueAt(i,0).toString());
                    pst.setString(2,jTable1.getValueAt(i,1).toString());
                    pst.setString(3,jTable1.getValueAt(i,2).toString());
                    pst.setString(4,jTable1.getValueAt(i,3).toString());
                    pst.setString(5,jTable1.getValueAt(i,4).toString());
                    pst.setString(6,jTable1.getValueAt(i,5).toString());
                    pst.setString(7,jTable1.getValueAt(i,6).toString());
                    pst.setString(8,jTable1.getValueAt(i,7).toString());
                    pst.setString(9,jTable1.getValueAt(i,8).toString());
                    pst.setString(10,jTable1.getValueAt(i,9).toString());
                    pst.setString(11,jTable1.getValueAt(i,10).toString());
                    pst.setString(12,jTable1.getValueAt(i,11).toString());
                    pst.setString(13,jTable1.getValueAt(i,12).toString());
                    pst.setString(14,jTable1.getValueAt(i,13).toString());
                    
                    pst.executeUpdate();                    
                }
                
                  for (int i = jTable1.getRowCount()-1; i>=0 ; i--) {
                    
                    modelo.removeRow(i);
                
                }
                JOptionPane.showMessageDialog(rootPane,"Se ha realizado el pedido correctamente");
                
            }catch(Exception ex){
                System.out.println(ex);
            }
            
        }
    
    /**
     * Creates new form Pedidos
     */
    public Pedidos() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_ot = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_Item = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcb_Pedidos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jcb_tipoPedidos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jcb_Solicita = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_Codigo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_Descripcion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_Tipo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_Referencia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_Marca = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_Unidad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_Cantidad = new javax.swing.JTextField();
        btn_Agregar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btn_Imprimir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_Enviar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pedidos");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("OT:");

        txt_ot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_otKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("ITEM:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("PEDIDO:");

        jcb_Pedidos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Consumibles Electricos", "Consumibles Mecanicos", "Pedido de equipos" }));
        jcb_Pedidos.setToolTipText("");
        jcb_Pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_PedidosActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("TIPO PEDIDO:");

        jcb_tipoPedidos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Pedido Inicial", "Pedido Adicional" }));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("SOLICITA:");

        jcb_Solicita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Ingenieria", "Comercial" }));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("CODIGO:");

        txt_Codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_CodigoKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("DESCRIPCION");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("TIPO:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("REFERENCIA:");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("MARCA:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("UNIDAD:");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("CANTIDAD:");

        btn_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-archivo.png"))); // NOI18N
        btn_Agregar.setPreferredSize(new java.awt.Dimension(44, 40));
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });

        btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });

        btn_Imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/impresora.png"))); // NOI18N
        btn_Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ImprimirActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OT", "ITEM", "CODIGO", "DESCRIPCION", "TIPO", "REFERENCIA", "MARCA", "UNIDAD", "CANTIDAD", "VALOR", "ADICIONAL_INICIAL", "FECHA", "OPERACION", "DEPARTAMENTO"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btn_Enviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/enviar-mensaje.png"))); // NOI18N
        btn_Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txt_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(309, 309, 309))
                            .addComponent(txt_Descripcion))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Referencia, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel9)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel10)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txt_Unidad, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 55, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ot, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15)
                        .addComponent(txt_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb_Pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb_tipoPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb_Solicita, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btn_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Imprimir)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Enviar)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_ot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jcb_Pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jcb_tipoPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jcb_Solicita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Referencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Unidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Eliminar)
                            .addComponent(btn_Imprimir))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Enviar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_PedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_PedidosActionPerformed
        // Insertar item a lista desplegable
        
    }//GEN-LAST:event_jcb_PedidosActionPerformed

    private void txt_otKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_otKeyPressed
        
    }//GEN-LAST:event_txt_otKeyPressed

    private void txt_CodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CodigoKeyPressed
          this.buscar();
    }//GEN-LAST:event_txt_CodigoKeyPressed

    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
        
        
    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        
        Calendar fecha = new GregorianCalendar();
        String dia = Integer.toString(fecha.get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(fecha.get(Calendar.MONTH) + 1);
        String year = Integer.toString(fecha.get(Calendar.YEAR));
        String date = (year+ "/" + mes+ "/" + dia);
        
        String []item=new String[14];
        item[0]=txt_ot.getText();
        item[1]=txt_Item.getText();
        item[2]=txt_Codigo.getText();
        item[3]=txt_Descripcion.getText();
        item[4]=txt_Tipo.getText();
        item[5]=txt_Referencia.getText();
        item[6]=txt_Marca.getText();
        item[7]=txt_Unidad.getText();
        item[8]=txt_Cantidad.getText();
        item[9]= Integer.toString(valor);
        item[10]=jcb_tipoPedidos.getSelectedItem().toString();
        item[11]=date;
        item[12]=jcb_Pedidos.getSelectedItem().toString();
        item[13]=jcb_Solicita.getSelectedItem().toString();
        modelo.addRow(item);
        jTable1.setModel(modelo);
                    
    }//GEN-LAST:event_btn_AgregarActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
                     
        if (jTable1.getSelectedRow()>=0) {
            int rpt = JOptionPane.showConfirmDialog(this, "Deseas eliminar este elemento","SISTEMA",JOptionPane.INFORMATION_MESSAGE);
            if (rpt==JOptionPane.YES_OPTION) {
                modelo.removeRow(jTable1.getSelectedRow());
            }
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione la fila que desea eliminar","SISTEMA",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void btn_ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ImprimirActionPerformed
        try {
            jTable1.print(); // Imprime el jTable
        } catch (PrinterException ex) { }
    
    }//GEN-LAST:event_btn_ImprimirActionPerformed

    private void btn_EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EnviarActionPerformed
        this.enviar();
    }//GEN-LAST:event_btn_EnviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_Enviar;
    private javax.swing.JButton btn_Imprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcb_Pedidos;
    private javax.swing.JComboBox<String> jcb_Solicita;
    private javax.swing.JComboBox<String> jcb_tipoPedidos;
    private javax.swing.JTextField txt_Cantidad;
    private javax.swing.JTextField txt_Codigo;
    private javax.swing.JTextField txt_Descripcion;
    private javax.swing.JTextField txt_Item;
    private javax.swing.JTextField txt_Marca;
    private javax.swing.JTextField txt_Referencia;
    private javax.swing.JTextField txt_Tipo;
    private javax.swing.JTextField txt_Unidad;
    private javax.swing.JTextField txt_ot;
    // End of variables declaration//GEN-END:variables
}
